name: 'CI'
on:
  push:

jobs:
  build:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install
        continue-on-error: false
        run: npm ci --immutable --immutable-cache --check-cache

      - name: Test
        continue-on-error: false
        run: npm run lint

      - name: Build app
        continue-on-error: false
        run: npm run build

      - name: Upload app artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: ./dist
          retention-days: 3

  deploy:
    needs: build
    if: github.event_name == 'push' && contains(github.ref, '/main')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Download app artifacts
        continue-on-error: false
        uses: actions/download-artifact@v4
        with:
          name: app
          path: ./dist

      - name: Deploy to GitHub Pages
        continue-on-error: false
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          email: ann.bystrova96@mail.ru
          build_dir: dist
